<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            ['id' => '1','title' => 'British Culture: An Introduction','slug' => 'british-culture-an-introduction','image' => 'http://localhost:8000/storage/images/product/Vt6cy9HBm2Jg3fKf.png','description' => 'British Culture: An Introduction provides a comprehensive introduction to central aspects of culture and the arts in Britain today, and uses a factual approach to place them within a clear, historical context.British Culture: An Introduction provides a comprehensive introduction to central aspects of culture and the arts in Britain today, and uses a factual approach to place them within a clear, historical context.Topics include:* the social and cultural setting: politics and society 1950-1999, including immigration, feminism, Thatcherism and the arts and the Blair revolution* language and culture: accents and minority languages, broadcasting and public life* the novel, poetry and theatre* cinema: Hammer Horror, James Bond, Ealing comedies, black British film, Trainspotting, The Full Monty and historical epics* television and radio: soap opera, crime series and sitcoms* popular music and fashion: The Beatles, punk, Britpop, subculture and style* art and sculpture: Bacon, Hockney, Gilbert and George and Hirst* architecture and interiors.Each chapter focuses on key themes of recent years, and gives special emphasis to outstanding artists within each area. The book also strengthens study skills, through follow-up activities and suggestions for further reading which appear at the end of each chapter. A real must-read for all students of British history and culture.','price' => '135.00','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 09:24:45','updated_at' => '2023-01-11 09:24:45','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '2','title' => 'British Music Hall: An Illustrated History','slug' => 'british-music-hall-an-illustrated-history','image' => 'http://localhost:8000/storage/images/product/oUnW1tUVCXKHSpAn.png','description' => '\'The music hall ...had no place for reticence; it was downright, it shouted, it made noise, it enjoyed itself and made the people enjoy themselves as well.\' W.J. MACQUEEN POPEMusic Hall lies at the root of all modern popular entertainment. With stars such as Marie Lloyd, Harry Lauder and Dan Leno, it reached its glorious, brassy height between 1890 and the First World War. In the first book on this subject for many years, Richard Anthony Baker whisks us off on a colourful and nostalgic tour of the rise and fall of British music hall.At the beginning of the nineteenth century people sang traditional songs in taverns for entertainment. This was so popular that rooms started to be added to inns for shows to be staged, and, before long, songs were being specially composed and purpose-built theatres were springing up everywhere. Britain\'s working class had, for the first time, its own form of public entertainment and its own breed of stars. The colour and vitality attracted serious writers and artists, as well as the future Edward VII, and music hall became simultaneously the haunt of the working classes and the avant-garde.Including stories of a clergyman who wrote music-hall sketches, a hall in Glasgow where luckless entertainers were pulled off stage by a long hooked pole, and Cockney dictionaries that helped Americans understand touring British performers, this book is a hugely engaging slice of social history, rich in humour, tragedy and bathos.As featured on BBC Radio Lincolnshire and in the Sunderland Echo.','price' => '11.49','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 10:14:13','updated_at' => '2023-01-11 10:14:13','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '3','title' => 'How the Scots Invented the Modern World','slug' => 'how-the-scots-invented-the-modern-world','image' => 'http://localhost:8000/storage/images/product/qPWIrKE3KCjCFBTF.png','description' => 'Who formed the first literate society? Who invented our modern ideas of democracy and free market capitalism? The Scots. As historian and author Arthur Herman reveals, in the eighteenth and nineteenth centuries Scotland made crucial contributions to science, philosophy, literature, education, medicine, commerce, and politics—contributions that have formed and nurtured the modern West ever since.

            Herman has charted a fascinating journey across the centuries of Scottish history. Here is the untold story of how John Knox and the Church of Scotland laid the foundation for our modern idea of democracy; how the Scottish Enlightenment helped to inspire both the American Revolution and the U.S. Constitution; and how thousands of Scottish immigrants left their homes to create the American frontier, the Australian outback, and the British Empire in India and Hong Kong.

            How the Scots Invented the Modern World reveals how Scottish genius for creating the basic ideas and institutions of modern life stamped the lives of a series of remarkable historical figures, from James Watt and Adam Smith to Andrew Carnegie and Arthur Conan Doyle, and how Scottish heroes continue to inspire our contemporary culture, from William “Braveheart” Wallace to James Bond.

            And no one who takes this incredible historical trek will ever view the Scots—or the modern West—in the same way again.','price' => '24.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 10:19:02','updated_at' => '2023-01-11 10:19:02','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '4','title' => 'Knots and Crosses','slug' => 'knots-and-crosses','image' => 'http://localhost:8000/storage/images/product/yLZmzlJl4GoQBldk.png','description' => 'Detective John Rebus’s city is being terrorized by a baffling series of murders…and he’s tied to a maniac by an invisible knot of blood. As the ghoulish killings mount and the tabloid headlines scream, Rebus cannot stop the feverish shrieks from within his own mind. Because he isn’t just one cop trying to catch a killer—he’s the man who’s got all the pieces to the puzzle….','price' => '99.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 10:21:52','updated_at' => '2023-01-11 10:21:52','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '5','title' => 'Scotland\'s Music: A History of the Traditional and Classic Music of Scotland','slug' => 'scotlands-music-a-history-of-the-traditional-and-classic-music-of-scotland','image' => 'http://localhost:8000/storage/images/product/hebDv7yhSsqjQz58.png','description' => 'Encompassing traditional, classical, and popular music and placing them in their historical contexts, this all-embracing account of the history of music and musicians in Scotland stretches from the Stone Age to the present day. Adding vital information to the history of Scotland itself, it is copiously illustrated with examples of music and images of musicians, manuscripts, and instruments. Much more than a second edition to its award-winning predecessor, the text and illustrations have been substantially revised and extended to take account of new discoveries and research. Additional information is included on the reconstruction of the carnyx and of other archaeological finds; further exposure of the musician spies attached to the exiled Mary Queen of Scots; the use of number symbolism by Scottish composers, which includes a direct bearing on the significance of the Darien Scheme; discussion of the work of Cecil Coles, whose last composition was found on his body after his death in the World War I; and examinations of many more composers and topics.','price' => '299.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 10:57:33','updated_at' => '2023-01-11 10:57:33','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '6','title' => 'The British Knight','slug' => 'the-british-knight','image' => 'http://localhost:8000/storage/images/product/PCZ16KGRotnHghW3.png','description' => 'When I’m offered the chance to leave New York to live in London for three months, I can’t pack my suitcase fast enough.

            As soon as I touch down I’m obsessing over red telephone boxes, palaces and all the black cabs. But my favorite place is the tube. It’s wall-to-wall hot British men in suits.

            When I’m offered a temporary job working for a barrister, I say, sign me up. On my first commute into work, it’s a total accident when I lose my balance and fall against the most handsome Brit alive. He’s as charming as James Bond and as suave as Mr. Darcy. I want to lick tea from his hard abs and listen to his accent all night long.

            Turns out Mr. Handsome is my new boss. And his attitude isn’t as hot as his gorgeous face, broad shoulders and tight ass. He’s brooding, short-tempered and the most arrogant man I’ve ever met.

            As we’re fighting, out of nowhere he kisses me. And I’m pretty sure I see fireworks over Big Ben and hear God Save the Queen. I wasn’t looking for the fairytale but I might have found my knight in shining armor.','price' => '24.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 10:58:59','updated_at' => '2023-01-11 10:58:59','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '7','title' => 'The Game of Kings','slug' => 'the-game-of-kings','image' => 'http://localhost:8000/storage/images/product/ZPZ5z7aQdIA3IkHX.png','description' => 'It is 1547 and Scotland has been humiliated by an English invasion and is threatened by machinations elsewhere beyond its borders, but it is still free. Paradoxically, her freedom may depend on a man who stands accused of treason. He is Francis Crawford of Lymond, a scapegrace nobleman of crooked felicities and murderous talents, posessed of a scholar\'s erudition and a tongue as wicked as a rapier. In The Game of Kings, this extraordinary antihero returns to the country that has outlawed him to redeem his reputations even at the risk of his life.','price' => '39.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 11:01:11','updated_at' => '2023-01-11 11:01:11','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '8','title' => 'The History And Poetry Of The Scottish Border','slug' => 'the-history-and-poetry-of-the-scottish-border','image' => 'http://localhost:8000/storage/images/product/P4D5fgXnVv5W3JgG.png','description' => 'This is a pre-1923 historical reproduction that was curated for quality. Quality assurance was conducted on each of these books in an attempt to remove books with imperfections introduced by the digitization process. Though we have made best efforts - the books may have occasional errors that do not impede the reading experience. We believe this work is culturally important and have elected to bring the book back into print as part of our continuing commitment to the preservation of printed works worldwide. This text refers to the Bibliobazaar edition.','price' => '24.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 11:02:43','updated_at' => '2023-01-11 11:02:43','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '9','title' => 'To the Lighthouse','slug' => 'to-the-lighthouse','image' => 'http://localhost:8000/storage/images/product/maiMpIL7a2EMh16z.png','description' => '“Radiant as [To the Lighthouse] is in its beauty, there could never be a mistake about it: here is a novel to the last degree severe and uncompromising. I think that beyond being about the very nature of reality, it is itself a vision of reality.”—Eudora Welty, from the Introduction.The serene and maternal Mrs. Ramsay, the tragic yet absurd Mr. Ramsay, and their children and assorted guests are on holiday on the Isle of Skye. From the seemingly trivial postponement of a visit to a nearby lighthouse, Woolf constructs a remarkable, moving examination of the complex tensions and allegiances of family life and the conflict between men','price' => '14.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 11:05:05','updated_at' => '2023-01-11 11:05:05','deleted_by' => NULL,'deleted_at' => NULL],
            ['id' => '10','title' => 'Wealth of the Nation: Scotland, Culture and Independence','slug' => 'wealth-of-the-nation-scotland-culture-and-independence','image' => 'http://localhost:8000/storage/images/product/NErIao4zRwHqCxIO.png','description' => 'The Wealth of the Nation explores how Scotland has continued to assert its distinctive cultural difference despite the three-hundred-year union with England and the modern forces of globalisation. Dealing with Scotland since the eighteenth century, the study analyses how Scottish culture defined itself within the British Empire and how, in the late twentieth century, it recovered from the collapse of the Empire to rebuild the value of its cultural past. Through its focus on the role of memory in philosophy, literature and the visual arts, readers will gain understanding of the influence that modern Scottish writers and artists have had on contemporary Scottish nationalism. The book argues that political nationalism in modern Scotland is founded on a cultural revival that began in the 1950s and 60s but gained momentum from resistance to the outcome of the 1979 devolution referendum. That resistance, and the creative achievements which it generated, provoked a re-examination of the nation’s cultural history, revealing a wealth previously denied or forgotten.','price' => '119.99','published' => '1','created_by' => '1','updated_by' => '1','created_at' => '2023-01-11 11:06:53','updated_at' => '2023-01-11 12:32:14','deleted_by' => NULL,'deleted_at' => NULL]
        ];

        Product::insert($products);
    }
}
